apiVersion: v1
kind: Secret
metadata:
  name: customers-secret
type: Opaque
stringData:
  database-url: jdbc:postgresql://postgres-service:5432/customers
  database-user: postgres
  database-password: postgres
